language: node_js

node_js: stable

before_install:
  - npm config set spin false --global

deploy:
  - provider: npm
    skip_cleanup: true
    email: "lee@leebyron.com"
    api_key:
      secure: "aN2Hz+7Z5sCbC9V5iGdjS3oKUMl5Ix0/9WuqxrJjAngPSQMchTXMsGW+XB+5vOeYqRS/lLRe9wUGfuwWUVgl3Pu4UOeHKApPryva55ImalIkcexCAynBJDEbPkW8HB36TAQIPu/h9xVhSuyYlq9BnApb9Jxfgy/oYsF49YXmed+BUOPaln9z0xSW1jP6mzkfzzg87C0UZhDB+D7IiPW6zPAWs9oDSHm9iC4PCW5PXcJqslC6qjMH3HCHuZI1FB419JoAlsiiKEgIq+cJt5BM/qYbui2N4CHP0EhRmPmg3pM4mpf3mf1JVz94XNCYQu9z2LQr6qiLv8sX+fzkDiLHYPJqqeGlqRre3mFUvP2HcUKpV+whhw0ljDV01JjhIEvGgEmTDBMhSlhd5lYjlZJvaaZH+WD+L9xYxAM6wRl/O9IuJ/J4WJ4ojLJTAP8T5hwKFTIGzBIkzWQnILeRv3eepEe1ZYMLiQb3tqRF+khzjGdCl2bD7no5qVW0ghKEHNzp9Tb9vKW4O3UN9xMibf10BSH6OeVoRVVdrnoWSP2Qc/fRBMoSJ14WOtc2GpFTso3cE+N3WF/e1sqDsq7DhqSMK3CHIrElPVd712vOUYltaoUkGWapkAUT8qwYaYf3XvKHnc+Uo4RGq5zyvWCqwTTsWYDVXRMqIwrnenOL7wlX9t0="
    on:
      tags: true
      branch: master
  - provider: releases
    skip_cleanup: true
    api_key:
      secure: "HzZELTrnObaY3L/Qf+sgxtzwZM8KpNNB3CzxHjkihIkl8bt2ibUgvPrArsUisyGI5WXiW6KMzyjDEmODjyT61InCUzXwdqtH7cpcYL1hLrCXUK1MH2yobesMlqcZiu1BdXgYPfhxA9BzA8aQmSmcnIj1+8nVh2ZRYcPE4Lct3eExzLKUr4hvDoGhfStEknLcuSaiICQXqVRQbnVclR/D5fZ77Nt/XdX6yTPd5+BqtEaLXM8rO1zCmD23QNrgHl9lOzIlc7hJ87TQ2t58f1l3nqxaDQieNGctM8ahrPHfYxKX2MZsuKgNEtBmsm+ldnaI2yKoFZNiBY4nEy35beqLROHihisxMo5+kw5L6f7aQ4YpI8lrmeWXUjHBIv9lpnuo8DVO2sBwhvywNhcHqLMX5wt6akh8HSdERpUxcA9cIPVY3vi3tGIJTxidxZUqFHM83Bvh54pss5Afi9HWodTIP+0/HtB7WdKBXH0F4CefuLDhy4aVb5tMo+bi1ENhjpdjl3o+VshkEYXOP2Ge8DAoatFqgXjrc/OQS+Ca7n/75dGwZVBGsX0Gg2Bp+zaWIp5xgqImclsBuk+879/tHUitxt4ZjkWH8E07voiU7WIrmw/BX/kQR3l5T1ROjjtJg1dGuRTSryjCzg+qx3ssXmf4szsaSgOTTPdMgI6HY5cJxEQ="
    file:
      - "graphiql.js"
      - "graphiql.min.js"
      - "graphiql.css"
    on:
      tags: true
      branch: master
