blank_issues_enabled: true
contact_links:
  - name: "ðŸ“š Support/Q&A"
    url: https://github.com/graphql/graphiql/discussions/categories/q-a-support
    about: >-
      Some questions are already answered in our github discussions Q&A section
      If you don't find an answer, [create a support ticket](ttps://github.com/graphql/graphiql/discussions/new?category=q-a-support)

  - name: "ðŸ’¬ `graphiql` Discord Support"
    url: https://discord.gg/NP5vbPeUFp
    about: "`graphiql` Discord Support Channel"

  - name: "ðŸ’¬ `vscode-graphql` Discord Support"
    url: https://discord.gg/bHrQtxGNzQ
    about: "`vscode-graphql` Discord Support Channel"

  - name: "ðŸ’¬ GraphQL LSP & CLI Discord Support"
    url: https://discord.gg/wkQCKwazxj
    about: >-
      GraphQL LSP (Language Server Protocol) Server Discord Support Channel 
      For `graphql-language-service-server` and/or `graphql-language-service-cli`

  - name: "ðŸ’¬ `monaco-graphql` Discord Support"
    url: https://discord.gg/r4BxrAG6fN
    about: "`monaco-graphql` Discord Support Channel"

  - name: "ðŸ’¬ `codedemirror-graphql` Discord Support"
    url: https://discord.gg/cffZwk8NJW
    about: "`codemirror-graphql` Discord Support Channel"
