name: Node.JS CI
on: [push]
jobs:
  test:
    name: lint & test
    runs-on: ubuntu-16.04
    steps:
      - uses: actions/checkout@v1
      - uses: bahmutov/npm-install@v1
      - run: yarn ci
  e2e:
    name: cypress
    runs-on: ubuntu-16.04
    steps:
      - uses: actions/checkout@v1
      - uses: bahmutov/npm-install@v1
      - run: yarn ci-e2e
