name: Node.JS CI Merge
on: [pull_request]
jobs:
  cleanup-branch:
    name: delete branch on PR merge
    runs-on: [ubuntu-16.04]
    steps:
     - uses: jessfraz/branch-cleanup-action@master
       env:
        NO_BRANCH_DELETED_EXIT_CODE: 0
