name: Lint & Build PR
on: 
  pull_request:
    types: [opened, synchronize]
      
jobs:
  lint:
    name: Lint
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
      - name: Use Node
        uses: actions/setup-node@v2

      - name: pnpm Install
        uses: bahmutov/npm-install@v1

      - name: Eslint
        run: pnpm lint

      - name: Prettier Check
        run: pnpm pretty-check

  build:
    name: Typescript Build
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
      - name: Use Node
        uses: actions/setup-node@v2
      - name: pnpm Install
        uses: bahmutov/npm-install@v1

      - name: Tyescript Build
        run: pnpm build
