name: Lint & Build PR
on: 
  pull_request:
    types: [opened, synchronize]
    # TODO: ignore this after setting up a separate task to link markdown
    # and to ignore eslint/prettier issues in examples
    paths-ignore:
      - '**.md'
      - 'examples/**'
      - '!examples/monaco-graphql-webpack'

      
jobs:
  lint:
    name: Lint
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 'current'
          cache: 'yarn'
      - run: yarn install --frozen-lockfile --immutable

      - name: Eslint
        run: yarn lint

      - name: Prettier Check
        run: yarn pretty-check

  build:
    name: Typescript Build
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 'current'
          cache: 'yarn'
      - run: yarn install --frozen-lockfile --immutable

      - name: Tyescript Build
        run: yarn build
