name: Build & Test PR w/ GraphQL Regressions
on:
  pull_request:
    types: [opened, synchronize]
    paths-ignore:
      - '**.md'
      - 'examples'
      - '!examples/monaco-graphql-webpack'

# TODO: test matrix?

jobs:
  build:
    name: Build & Test
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        release: ['15.5.3', '^15.8.0', '16.1.0', '16.2.0', '16.3.0']
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - uses: actions/setup-node@v3
        with:
          node-version: 'current'
          cache: 'yarn'

      - name: Force GraphQL ${{ matrix.release }} solution
        run: yarn repo:resolve graphql@${{ matrix.release }}
    
      - run: yarn install --frozen-lockfile --immutable

      - name: Typescript Build
        run: yarn build

      - name: Unit Tests
        run: yarn test

      - name: Cypress
        run: yarn e2e
