name: Build & Test PR w/ GraphQL Regressions
on:
  pull_request:
    types: [opened, synchronize]
    paths-ignore:
      - '**.md'
      - 'examples'
      - '!examples/monaco-graphql-webpack'

# TODO: test matrix?

jobs:
  build:
    name: Build & Test
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        release: ['15.5.3', '^15.8.0', '16.1.0', '16.2.0', '16.3.0']
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Use Node
        uses: actions/setup-node@v2

      - name: Force GraphQL 15 resolution
        run: yarn repo:resolve graphql@${{ matrix.release }}

      - name: Yarn Install
        uses: bahmutov/npm-install@v1  

      - name: Typescript Build
        run: yarn build

      - name: Unit Tests
        run: yarn test

      - name: Cypress
        run: yarn e2e
