name: Test PR
on:
  pull_request:
    types: [opened, synchronize]
    paths-ignore:
      - '**.md'
      - 'examples/**'
      - '!examples/monaco-graphql-webpack'
jobs:
  unit:
    name: Unit Tests
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 'current'
          cache: 'yarn'
      - run: yarn install --frozen-lockfile --immutable

      - name: Build
        run: yarn build

      - name: Run Unit Tests
        run: yarn test

  e2e:
    name: Cypress E2E Suite
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '16.x'
          cache: 'yarn'
      - run: yarn install --frozen-lockfile --immutable

      - name: Run E2E suite
        run: yarn e2e
