name: automatic-release

on:
  push:
    branches-ignore:
      - master

env:
  BOT_GH_TOKEN: ${{ secrets.BOT_GH_TOKEN }}
  VSCE_PAT: ${{ secrets.VSCE_PAT }}

jobs:
  prerelease:
    if: endsWith(github.ref, '/master')!
    name: Create prerelease
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install Dependencies
        run: npm ci

      - name: Setup GIT
        run: |
          git config --global user.email "95909575+graphql-bot@users.noreply.github.com"
          git config --global user.name "GraphQL Bot"
          git remote add github "https://$GITHUB_ACTOR:$BOT_GH_TOKEN@github.com/$GITHUB_REPOSITORY.git" || true

      - name: Bump version
        id: bump
        run: |
          npm version patch

      - name: VSCE Pre-Release Publish
        id: publish
        run: |
          ./node_modules/.bin/vsce publish --pre-release

      - name: Push to master
        run: |
          git push github HEAD:"${GITHUB_REF}"
