name: Automatic Publish to open-vsx.org

on:
  workflow_run:
    workflows: ["automatic-release"]
    branches: [master]
    types:
      - completed
  workflow_dispatch:

env:
  GH_TOKEN: ${{ secrets.GH_TOKEN }}
  OPEN_VSX_ACCESS_TOKEN: ${{ secrets.OPEN_VSX_ACCESS_TOKEN }}

jobs:
  publish:
    if: endsWith(github.ref, '/master')
    name: Publish
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install Dependencies
        run: npm ci
      - name: Publish Extension as Patch to open-vsx
        run: node_modules/.bin/ovsx publish -p "$OPEN_VSX_ACCESS_TOKEN"
