name: Automatic Publish to Marketplace

on:
  workflow_run:
    workflows: ["automatic-release"]
    branches: [master]
    types:
      - completed
  workflow_dispatch:

env:
  VSCE_PAT: ${{ secrets.VSCE_PAT }}

jobs:
  publish:
    if: endsWith(github.ref, '/master')
    name: Publish
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install Dependencies
        run: npm install
      - name: Publish Extension as Patch to marketplace
        run: |
          ./node_modules/.bin/vsce publish
